### ISSUE TITLE
Add parameter for crosshair placement

### ISSUE THREAD

**Issue by danduk82** [geoadmin/web-mapviewer#451]
Hello,
in the context of the BFS application "AREApp" which is a custom application that is used to generate the statistics about land usage and land coverage, there are some windows which include map.geo.admin.ch as auxiliary information.

The interpreters who use the software check all the points of the surveillance network (one each 100m), and when they click on "next" in the AREApp application, all the maps are re-centered on the new point.

Planning the migration to the new web-viewer when it will replace the current geoadmin3, I did a couple of test for the recentering of the map. Changing the lat and lon parameter does not reload the application, which is great for improved perfomance. But we need also to place a crosshair with `crosshair=cross` so that the users can locate the surveillance point on the map, and this forces us to reload the whole application anyway.

It would be great to have a similar parameter set, like `crosslat=46.0&crosslong=35.0` available in the url to recenter the crosshair location.

So, a few questions now:
- How much effort would be needed to implement this in your opinion?
- Do you think that this makes sense?
- Can you point out a couple of lines in the current code where we should check if we get a bit of budget to implement it?

**Comment by pakb** [comment]
Hello,
you could get by without having to develop this new parameters, by removing it and adding `crosshair` back it will be re-placed at the center of the viewport once again (or maybe change its value between two possible values)

Otherwise a good starting point would be to : 

- create a entry in the `position.store.js` file
- link it to two new URL params in `storeSync.config.js`
- modify `OpenLayersMap.vue` to use this new position (instead of the `initialPosition` currently used)

Just bare in mind that this new store entry should be set to the starting center of the view if nothing is defined in the URL parameters

**Comment by claudiof2023** [comment]
Hi,
I'm working with Andrea on this topic, at the swiss federal office.

I followed your instructions on the url usage, but can't move the cursor as suggested:

First call: 
https://test.map.geo.admin.ch/#/map?lang=fr&lat=47.0&lon=7.0&z=10.0&bgLayer=ch.swisstopo.pixelkarte-farbe&topic=ech&swisssearch=SWISSIMAGE+Voyage+dans+le+temps&crosshair=cross&layers=ch.swisstopo.zeitreihen@year=1864,f;ch.bfs.gebaeude_wohnungs_register,f;ch.bav.haltestellen-oev,f;ch.swisstopo.swisstlm3d-wanderwege,f;ch.astra.wanderland-sperrungen_umleitungen,f;ch.swisstopo.lubis-luftbilder_farbe@year=9999;ch.swisstopo.swissimage-product@year=9999

Then neither of these 2 calls will replace the crosshair:

https://test.map.geo.admin.ch/#/map?lang=fr&lat=47.1&lon=7.0&z=10.0&bgLayer=ch.swisstopo.pixelkarte-farbe&topic=ech&swisssearch=SWISSIMAGE+Voyage+dans+le+temps&crosshair=cross&layers=ch.swisstopo.zeitreihen@year=1864,f;ch.bfs.gebaeude_wohnungs_register,f;ch.bav.haltestellen-oev,f;ch.swisstopo.swisstlm3d-wanderwege,f;ch.astra.wanderland-sperrungen_umleitungen,f;ch.swisstopo.lubis-luftbilder_farbe@year=9999;ch.swisstopo.swissimage-product@year=9999

https://test.map.geo.admin.ch/#/map?lang=fr&lat=47.1&lon=7.1&z=10.0&bgLayer=ch.swisstopo.pixelkarte-farbe&topic=ech&swisssearch=SWISSIMAGE+Voyage+dans+le+temps&crosshair=point&layers=ch.swisstopo.zeitreihen@year=1864,f;ch.bfs.gebaeude_wohnungs_register,f;ch.bav.haltestellen-oev,f;ch.swisstopo.swisstlm3d-wanderwege,f;ch.astra.wanderland-sperrungen_umleitungen,f;ch.swisstopo.lubis-luftbilder_farbe@year=9999;ch.swisstopo.swissimage-product@year=9999

Is there anything wrong in my test?

Br

**Comment by pakb** [comment]
I see that there is something not working as intended here.
We are right in the process of changing how our projection system are handled, so I can't promise you a quick delivery, but I've already prepared some ground work for this to function properly (we just need to wait for the big projection work to come to `develop` and that I adapt it)

See #491 if you want to make some local test already

**Comment by claudiof2023** [comment]
Many thanks for handling this "dynamic crosshair" correction. It's quite important for the application supporting Arealstatistik à the FSO, but not necessary before the release date of the new version of the map viewer.

We don't have a local environment, but we can of course test once on test.map.admin.ch.

**Comment by pakb** [comment]
Will be deployed on https://test.map.geo.admin.ch/ with the next push there, we've to fix a couple things in 3D before deploying

**Comment by pakb** [comment]
Has been deployed on the test viewer

**Comment by claudiof2023** [comment]
Thank you very much! I just tested it. The dynamic crosshair works beautifully using something like the following URL and just updating the coordinates:
https://test.map.geo.admin.ch/#/map?lang=fr&center=2496800,1120900&z=10&bgLayer=ch.swisstopo.pixelkarte-farbe&topic=ech&swisssearch=SWISSIMAGE+Voyage+dans+le+temps&crosshair=cross&layers=ch.swisstopo.zeitreihen@year=1864,f;ch.bfs.gebaeude_wohnungs_register,f.

I just have a question on the coordinates parameters though: if I enter &lat and &lon in WGS84, instead of &center in LV95, it centers the map correctly but doesn't react to a coordinates update. If I refresh the page it converts it to &center in LV95. 

We can use &center in LV95, but just for our understanding, is this expected?

**Comment by pakb** [comment]
I don't know if you've noticed, but you can re-position the crosshair by setting the param so that `&crosshair=type,X,Y`, no need to use the `&center=...` and then swap back and forth `&crosshair=`

**Comment by claudiof2023** [comment]
Thanks for the advices! Very good.
